# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_name', models.CharField(max_length=45, unique=True, verbose_name='Nome da palestra')),
                ('talk_description', models.CharField(max_length=90, verbose_name='Descrição da palestra')),
                ('speaker_name', models.CharField(max_length=45, verbose_name='Nome do palestrante')),
                ('speaker_description', models.CharField(max_length=45, null=True, verbose_name='Sobre o palestrante')),
                ('local', models.CharField(help_text='Exemplo: Bloco X', max_length=30, verbose_name='Prédio/Bloco da palestra')),
                ('room', models.CharField(max_length=30, verbose_name='Sala da palestra')),
                ('date', models.DateField(verbose_name='Data')),
                ('hour', models.TimeField(verbose_name='Horário')),
                ('number_vacancies', models.SmallIntegerField(verbose_name='Vagas')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modification', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['talk_name', 'speaker_name'])),
            ],
        ),
    ]
