# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestrante',
            name='show_home',
            field=models.BooleanField(default=None, verbose_name='Mostrar na pagina inicial?'),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='number_vacancies',
            field=models.SmallIntegerField(default=100, verbose_name='Vagas'),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='image',
            field=models.ImageField(default='speaker-1.png', upload_to='palestrante/%Y'),
        ),
    ]
