# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20171021_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='palestrante',
            field=models.ManyToManyField(to='dash.Palestrante'),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['talk_name', 'room']),
        ),
    ]
