# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_remove_palestrante_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestrante',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar na pagina inicial?'),
        ),
    ]
