# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_palestrante_show_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestrante',
            name='speaker_description',
            field=models.TextField(max_length=120, null=True, verbose_name='Sobre o palestrante'),
        ),
    ]
