# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_auto_20171030_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nome')),
                ('age', models.SmallIntegerField(verbose_name='Idade')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('document', models.CharField(max_length=14, verbose_name='CPF')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Palestra')),
            ],
        ),
    ]
