# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_registred'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Meetup'), (2, 'Cursos'), (3, 'Demonstrações'), (4, 'Apresentações')], default=1),
        ),
    ]
