# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_palestra_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='hour_end',
            field=models.TimeField(help_text='HH/MM', verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='hour_init',
            field=models.TimeField(help_text='HH/MM', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Meetup'), (2, 'Curso'), (3, 'Demonstração'), (4, 'Apresentação')], default=4, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='registred',
            name='document',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.RemoveField(
            model_name='registred',
            name='palestra',
        ),
        migrations.AddField(
            model_name='registred',
            name='palestra',
            field=models.ManyToManyField(to='dash.Palestra'),
        ),
    ]
