# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_auto_20171031_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palestra',
            options={'verbose_name': 'Palestra cadastrada', 'verbose_name_plural': 'Palestras cadastrados'},
        ),
        migrations.AlterModelOptions(
            name='palestrante',
            options={'verbose_name': 'Palestrante cadastrado', 'verbose_name_plural': 'Palestrantes cadastrados'},
        ),
        migrations.AlterModelOptions(
            name='registred',
            options={'verbose_name': 'Estudante cadastrado', 'verbose_name_plural': 'Estudantes cadastrados'},
        ),
    ]
